# Site settings
title: huibiaoli's blog
email: huibiaoli@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://huibiaoli.github.io" # the base hostname & protocol for your site
twitter_username: huibiaoli
github_username:  huibiaoli

# Build settings
markdown: kramdown
pygments: true
